name: ci(smoke): v4 — ubuntu + curl (manual e tag)

on:
  workflow_dispatch: {}
  push:
    tags:
      - "smoke-*"

permissions:
  contents: read

jobs:
  health:
    name: GET /api/health (prod)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping health
        shell: bash
        run: |
          set -euo pipefail
          URL="https://bags-shield-api.vercel.app/api/health"
          echo "Ping: ${URL}"
          HTTP=$(curl -sS -o /dev/null -w "%{http_code}" "${URL}" || true)
          echo "HTTP=${HTTP}"
          test "${HTTP}" = "200" || { echo "Health check falhou (HTTP=${HTTP})"; exit 1; }

      - name: Dump contexto (sempre)
        if: always()
        shell: bash
        run: |
          echo "ref=$GITHUB_REF"
          echo "sha=$GITHUB_SHA"
          echo "event=$GITHUB_EVENT_NAME"