name: ci(smoke): manual-smoke (v6)

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [manual_smoke]

permissions:
  contents: read

jobs:
  hello:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Hello
        shell: bash
        run: echo "hello $GITHUB_SHA @ $(date -u)"